# Mining the Social Web 2nd Edition
---
- hosts: 127.0.0.1
  sudo: yes
  connection: local
  tasks:
    - apt: pkg=openjdk-6-jdk
    - name: Install MongoDB
      apt: pkg=mongodb state=latest
    - name: Create /data/db/ directory for MongoDB
      file: path=/data/db state=directory owner={{dst_username}} group={{dst_username}}
    - name: Enable MongoDB text search
      lineinfile: >
        dest=/etc/mongodb.conf
        state=present
        insertafter=EOF
        line="setParameter=textSearchEnabled=true"
      notify: restart mongodb
    - name: Install Python packages
      pip: name={{item}} state=latest
      with_items:
        - BeautifulSoup
        - Flask
        - Jinja2
        - PyGithub
        - PyYAML
        - Werkzeug
        - beautifulsoup4
        - chardet
        - cluster
        - envoy
        - facebook-sdk
        - feedparser
        - geopy
        - google-api-python-client
        - httplib2
        - networkx
        - nltk
        - oauthlib
        - prettytable
        - pymongo
        - python-dateutil
        - python-gflags
        - python-linkedin
        - readline
        - requests
        - requests-oauthlib
        - tornado
        - twitter
        - wsgiref
        - oauth2
        - twitter-text-py
        - JPype1
        - charade
        - boilerpipe
        - "http://cheeseshop.python.org/packages/source/p/pyparsing/pyparsing-1.5.5.tar.gz"
        - "https://fuxi.googlecode.com/hg/layercake-python.tar.bz2"
        - "https://pypi.python.org/packages/source/F/FuXi/FuXi-1.4.1.production.tar.gz"
    - name: Make sure that the notebooks directory exists
      file: path=/home/{{ dst_username }}/notebooks state=directory owner={{ dst_username }} group={{ dst_username }}
    - name: Clone the Mining the Social Web repository
      git: repo=https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition.git dest=/tmp/mtsw2e
    - name: Copy IPython notebooks
      copy: src="{{item}}" dest=/home/{{ dst_username }}/notebooks owner={{ dst_username }} group={{ dst_username }}
      with_fileglob: '/tmp/mtsw2e/ipynb/*'
    - name: Copy IPython notebook html and resources
      copy: src="/tmp/mtsw2e/ipynb/{{item}}" dest=/home/{{ dst_username }}/notebooks
      with_items:
        - html
        - resources
    - name: Make sure that the notebooks have the correct permissions
      file: path=/home/{{ dst_username }}/notebooks/{{item}} state=directory owner={{ dst_username }} group={{ dst_username }} recurse=yes
      with_items:
        - html
        - resources

  handlers:
    - name: restart mongodb
      service: name=mongodb state=restarted
