---
- hosts: 127.0.0.1
  sudo: yes
  connection: local
  tasks:
    - name: Configure Go
      shell: echo 'golang-go golang-go/dashboard boolean true' > /tmp/preseed.conf
    - shell: debconf-set-selections /tmp/preseed.conf
    - name: Add repository for node.js
      apt_repository: repo='ppa:chris-lea/node.js' update-cache=yes
    - name: Install Ubuntu packages
      apt: pkg={{item}} state=latest
      with_items:
        - parallel
        - libxml2-dev
        - libxslt1-dev
        - golang-go
        - nodejs
        - make
        - curl
        - g++
        - python-software-properties 
        - p7zip-full
        - unrar-free
        - unzip
    - name: Get command-line tools for data science
      git: repo=https://github.com/jeroenjanssens/command-line-tools-for-data-science.git dest=/home/{{ dst_username }}/repos/command-line-tools-for-data-science/
    - name: Make sure that the tools directory exists
      file: path=/home/{{ dst_username }}/tools state=directory owner={{ dst_username }} group={{ dst_username }}
    - name: Install jq
      get_url: url=http://stedolan.github.io/jq/download/linux64/jq dest=/home/{{ dst_username }}/tools/jq mode=0755 owner={{ dst_username }} group={{ dst_username }}
    - shell: sudo GOPATH=/home/{{ dst_username }}/.go go get github.com/jehiah/json2csv
    - name: Get npm
      get_url: url=http://npmjs.org/install.sh dest=/tmp/install.sh
    - name: Install npm
      shell: sudo clean=yes sh /tmp/install.sh
    - name: Install xml2json
      npm: name=xml2json-command global=yes
    - name: Install Python packages
      pip: name={{item}} state=latest
      with_items:
        - awscli
        - csvkit
        - cssselect
        - lxml
    - name: Update PATH
      lineinfile: >
        dest=/etc/environment
        state=present
        backrefs=yes
        regexp='PATH=(["]*)((?!.*?{{ item }}).*?)(["]*)$'
        line='PATH=\1\2:{{ item }}\3'
      with_items:
        - '/home/{{ dst_username }}/repos/command-line-tools-for-data-science/tools'
        - '/home/{{ dst_username }}/tools'
        - '/usr/lib/go/bin'
        - '/home/{{ dst_username }}/.go/bin'
    - name: Load PATH
      shell: export $(cat /etc/environment | tr -d \")
      sudo: no
